vim.cmd([[highlight clear]])
if vim.fn.exists("syntax_on") then
  vim.cmd([[syntax reset]])
end

vim.g.colors_name = "dark-pastel"

local bg       = "#000000"
local fg       = "#ffffff"
local black    = "#000000"
local red      = "#ff5555"
local green    = "#55ff55"
local yellow   = "#ffff55"
local blue     = "#5555ff"
local magenta  = "#ff55ff"
local cyan     = "#55ffff"
local white    = "#bbbbbb"
local br_black = "#555555"
local br_red   = "#ff5555"
local br_green = "#55ff55"
local br_yellow= "#ffff55"
local br_blue  = "#5555ff"
local br_magenta="#ff55ff"
local br_cyan  = "#55ffff"
local br_white = "#ffffff"
local sel_bg  = "#b5d5ff"
local sel_fg  = "#000000"

local hi = vim.api.nvim_set_hl

hi(0, "Normal",        { fg = fg, bg = bg })
hi(0, "NormalFloat",   { fg = fg, bg = "#111111" })
hi(0, "FloatBorder",   { fg = white, bg = "#111111" })
hi(0, "Comment",       { fg = br_black, italic = true })
hi(0, "Constant",      { fg = cyan })
hi(0, "String",        { fg = green })
hi(0, "Character",     { fg = green })
hi(0, "Number",        { fg = magenta })
hi(0, "Float",         { fg = magenta })
hi(0, "Boolean",       { fg = magenta })
hi(0, "Identifier",    { fg = fg })
hi(0, "Function",      { fg = yellow })
hi(0, "Statement",     { fg = red })
hi(0, "Conditional",   { fg = red })
hi(0, "Repeat",        { fg = red })
hi(0, "Label",         { fg = red })
hi(0, "Operator",      { fg = cyan })
hi(0, "Keyword",       { fg = red })
hi(0, "Exception",     { fg = red })
hi(0, "PreProc",       { fg = blue })
hi(0, "Include",       { fg = blue })
hi(0, "Define",        { fg = blue })
hi(0, "Macro",         { fg = blue })
hi(0, "PreCondit",     { fg = blue })
hi(0, "Type",          { fg = yellow })
hi(0, "StorageClass",  { fg = yellow })
hi(0, "Structure",     { fg = cyan })
hi(0, "Typedef",       { fg = yellow })
hi(0, "Special",       { fg = br_magenta })
hi(0, "SpecialChar",   { fg = magenta })
hi(0, "Tag",           { fg = green })
hi(0, "Delimiter",     { fg = fg })
hi(0, "SpecialComment", { fg = br_black, italic = true })
hi(0, "Debug",         { fg = red })
hi(0, "Underlined",    { fg = blue, underline = true })
hi(0, "Ignore",        { fg = br_black })
hi(0, "Error",         { fg = red, bg = bg })
hi(0, "Todo",          { fg = yellow, bg = bg, bold = true })

hi(0, "Visual",        { fg = sel_fg, bg = sel_bg })
hi(0, "VisualNOS",     { fg = sel_fg, bg = sel_bg })
hi(0, "Cursor",         { fg = bg, bg = white })
hi(0, "CursorLine",    { bg = "#111111" })
hi(0, "CursorColumn",  { bg = "#111111" })
hi(0, "CursorLineNr",  { fg = yellow, bold = true })
hi(0, "LineNr",        { fg = br_black })
hi(0, "SignColumn",    { fg = br_black, bg = bg })
hi(0, "FoldColumn",    { fg = br_black, bg = bg })
hi(0, "Folded",        { fg = br_black, bg = "#111111", italic = true })
hi(0, "MatchParen",    { fg = red, bg = bg, bold = true })
hi(0, "Search",        { fg = sel_fg, bg = sel_bg })
hi(0, "IncSearch",     { fg = sel_fg, bg = sel_bg })
hi(0, "Substitute",    { fg = sel_fg, bg = sel_bg })
hi(0, "Pmenu",         { fg = fg, bg = "#111111" })
hi(0, "PmenuSel",      { fg = sel_fg, bg = br_blue })
hi(0, "PmenuSbar",     { bg = br_black })
hi(0, "PmenuThumb",    { bg = white })
hi(0, "WildMenu",      { fg = sel_fg, bg = sel_bg })
hi(0, "TabLine",       { fg = white, bg = "#111111" })
hi(0, "TabLineFill",   { fg = br_black, bg = bg })
hi(0, "TabLineSel",    { fg = yellow, bg = bg, bold = true })
hi(0, "StatusLine",    { fg = fg, bg = "#111111" })
hi(0, "StatusLineNC",  { fg = br_black, bg = "#080808" })
hi(0, "VertSplit",     { fg = br_black, bg = bg })
hi(0, "WinSeparator", { fg = br_black, bg = bg })
hi(0, "Title",         { fg = yellow, bold = true })
hi(0, "Directory",     { fg = blue })
hi(0, "NonText",       { fg = br_black })
hi(0, "SpecialKey",    { fg = br_black })
hi(0, "Conceal",       { fg = br_black })
hi(0, "EndOfBuffer",   { fg = br_black })
hi(0, "Whitespace",   { fg = br_black })

hi(0, "DiffAdd",    { fg = green, bg = "#002200" })
hi(0, "DiffChange", { fg = yellow, bg = "#222200" })
hi(0, "DiffDelete", { fg = red, bg = "#220000" })
hi(0, "DiffText",   { fg = yellow, bg = "#333300" })

hi(0, "SpellBad",   { undercurl = true, sp = red })
hi(0, "SpellCap",   { undercurl = true, sp = yellow })
hi(0, "SpellLocal", { undercurl = true, sp = cyan })
hi(0, "SpellRare",  { undercurl = true, sp = magenta })

hi(0, "DiagnosticError", { fg = red })
hi(0, "DiagnosticWarn",  { fg = yellow })
hi(0, "DiagnosticInfo",  { fg = cyan })
hi(0, "DiagnosticHint",  { fg = blue })
hi(0, "DiagnosticSignError", { fg = red })
hi(0, "DiagnosticSignWarn",  { fg = yellow })
hi(0, "DiagnosticSignInfo",  { fg = cyan })
hi(0, "DiagnosticSignHint",  { fg = blue })
hi(0, "DiagnosticUnderlineError", { undercurl = true, sp = red })
hi(0, "DiagnosticUnderlineWarn",  { undercurl = true, sp = yellow })
hi(0, "DiagnosticUnderlineInfo",  { undercurl = true, sp = cyan })
hi(0, "DiagnosticUnderlineHint",  { undercurl = true, sp = blue })

hi(0, "GitSignsAdd",    { fg = green })
hi(0, "GitSignsChange", { fg = yellow })
hi(0, "GitSignsDelete", { fg = red })

hi(0, "@keyword",       { fg = red })
hi(0, "@keyword.function", { fg = red })
hi(0, "@keyword.operator", { fg = red })
hi(0, "@keyword.return",  { fg = red })
hi(0, "@conditional",   { fg = red })
hi(0, "@repeat",        { fg = red })
hi(0, "@exception",     { fg = red })
hi(0, "@function",      { fg = yellow })
hi(0, "@function.call",  { fg = yellow })
hi(0, "@function.builtin", { fg = cyan })
hi(0, "@method",        { fg = yellow })
hi(0, "@method.call",   { fg = yellow })
hi(0, "@constructor",   { fg = cyan })
hi(0, "@variable",      { fg = fg })
hi(0, "@variable.builtin", { fg = magenta })
hi(0, "@variable.member", { fg = fg })
hi(0, "@parameter",     { fg = fg })
hi(0, "@property",      { fg = cyan })
hi(0, "@field",         { fg = cyan })
hi(0, "@type",          { fg = yellow })
hi(0, "@type.builtin",  { fg = yellow })
hi(0, "@type.definition", { fg = yellow })
hi(0, "@class",         { fg = yellow })
hi(0, "@namespace",     { fg = yellow })
hi(0, "@module",        { fg = yellow })
hi(0, "@string",        { fg = green })
hi(0, "@string.escape",  { fg = magenta })
hi(0, "@string.special", { fg = magenta })
hi(0, "@character",     { fg = green })
hi(0, "@character.special", { fg = magenta })
hi(0, "@number",        { fg = magenta })
hi(0, "@float",         { fg = magenta })
hi(0, "@boolean",       { fg = magenta })
hi(0, "@constant",      { fg = cyan })
hi(0, "@constant.builtin", { fg = magenta })
hi(0, "@constant.macro",  { fg = blue })
hi(0, "@label",         { fg = red })
hi(0, "@operator",      { fg = cyan })
hi(0, "@punctuation",   { fg = fg })
hi(0, "@punctuation.bracket", { fg = fg })
hi(0, "@punctuation.delimiter", { fg = fg })
hi(0, "@punctuation.special",  { fg = magenta })
hi(0, "@comment",       { fg = br_black, italic = true })
hi(0, "@comment.documentation", { fg = br_black, italic = true })
hi(0, "@tag",           { fg = red })
hi(0, "@tag.attribute", { fg = cyan })
hi(0, "@tag.delimiter", { fg = br_black })
hi(0, "@attribute",     { fg = blue })
hi(0, "@annotation",    { fg = magenta })
hi(0, "@text",          { fg = fg })
hi(0, "@text.strong",   { fg = fg, bold = true })
hi(0, "@text.emphasis", { fg = fg, italic = true })
hi(0, "@text.underline", { fg = blue, underline = true })
hi(0, "@text.title",    { fg = yellow, bold = true })
hi(0, "@text.literal",  { fg = green })
hi(0, "@text.reference", { fg = blue })
hi(0, "@text.uri",      { fg = cyan, underline = true })
hi(0, "@math",          { fg = magenta })
hi(0, "@markup.heading",    { fg = yellow, bold = true })
hi(0, "@markup.link",       { fg = blue })
hi(0, "@markup.link.url",   { fg = cyan, underline = true })
hi(0, "@markup.link.label", { fg = green })
hi(0, "@markup.list",       { fg = red })
hi(0, "@markup.list.checked",   { fg = green })
hi(0, "@markup.list.unchecked",  { fg = br_black })
hi(0, "@markup.italic",     { fg = fg, italic = true })
hi(0, "@markup.bold",       { fg = fg, bold = true })
hi(0, "@markup.strikethrough", { fg = br_black, strikethrough = true })
hi(0, "@markup.raw",        { fg = green })
hi(0, "@diff.plus",         { fg = green })
hi(0, "@diff.minus",        { fg = red })
hi(0, "@diff.delta",        { fg = yellow })

hi(0, "NotifyERRORBorder", { fg = red })
hi(0, "NotifyWARNBorder",  { fg = yellow })
hi(0, "NotifyINFOBorder",  { fg = cyan })
hi(0, "NotifyDEBUGBorder",  { fg = br_black })
hi(0, "NotifyTRACEBorder", { fg = br_black })
hi(0, "NotifyERRORIcon",   { fg = red })
hi(0, "NotifyWARNIcon",    { fg = yellow })
hi(0, "NotifyINFOIcon",    { fg = cyan })
hi(0, "NotifyDEBUGIcon",   { fg = br_black })
hi(0, "NotifyTRACEIcon",   { fg = br_black })
hi(0, "NotifyERRORTitle",  { fg = red })
hi(0, "NotifyWARNTitle",   { fg = yellow })
hi(0, "NotifyINFOTitle",   { fg = cyan })
hi(0, "NotifyDEBUGTitle",  { fg = br_black })
hi(0, "NotifyTRACETitle",  { fg = br_black })

hi(0, "NoiceCmdlineIcon",  { fg = yellow })
hi(0, "NoiceCmdlinePopupBorder", { fg = br_black })
hi(0, "NoiceCmdlinePrompt", { fg = yellow })

hi(0, "MiniFilesNormal",   { fg = fg, bg = bg })
hi(0, "MiniFilesTitle",     { fg = yellow })
hi(0, "MiniFilesBorder",    { fg = br_black })
hi(0, "MiniFilesCursorLine",{ bg = "#111111" })

hi(0, "TelescopeBorder",    { fg = br_black })
hi(0, "TelescopePromptBorder", { fg = br_black })
hi(0, "TelescopeResultsBorder", { fg = br_black })
hi(0, "TelescopePreviewBorder", { fg = br_black })
hi(0, "TelescopeTitle",     { fg = yellow })
hi(0, "TelescopePromptTitle", { fg = yellow })
hi(0, "TelescopeResultsTitle", { fg = yellow })
hi(0, "TelescopePreviewTitle", { fg = yellow })
hi(0, "TelescopeMatching",  { fg = red, bold = true })
hi(0, "TelescopeSelection", { fg = sel_fg, bg = sel_bg })
hi(0, "TelescopeSelectionCaret", { fg = red })
hi(0, "TelescopeMultiIcon", { fg = red })

hi(0, "LazyButton",      { fg = fg, bg = "#111111" })
hi(0, "LazyButtonActive",{ fg = yellow, bg = "#111111", bold = true })
hi(0, "LazySpecial",     { fg = cyan })

hi(0, "WhichKeyNormal",  { fg = fg, bg = bg })
hi(0, "WhichKeyBorder",  { fg = br_black })
hi(0, "WhichKeyGroup",   { fg = yellow })
hi(0, "WhichKeyDesc",    { fg = fg })
hi(0, "WhichKeySeperator", { fg = br_black })

hi(0, "BlinkCmpLabel",        { fg = fg })
hi(0, "BlinkCmpLabelMatch",   { fg = red, bold = true })
hi(0, "BlinkCmpKind",         { fg = br_black })
hi(0, "BlinkCmpKindFunction", { fg = yellow })
hi(0, "BlinkCmpKindVariable", { fg = fg })
hi(0, "BlinkCmpKindClass",    { fg = yellow })
hi(0, "BlinkCmpKindModule",   { fg = yellow })
hi(0, "BlinkCmpKindKeyword",  { fg = red })
hi(0, "BlinkCmpKindSnippet",  { fg = cyan })
hi(0, "BlinkCmpKindFile",     { fg = green })

hi(0, "TreesitterContext", { bg = "#111111" })
hi(0, "TreesitterContextLineNumber", { fg = br_black })